import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header1 from "./components/Headers/Header1";
import Header2 from "./components/Headers/Header2";
import Footer from "./components/Footer/Footer";

import { Josefin_Sans } from "next/font/google"

const joseFin = Josefin_Sans({
  subsets: ["latin"],
});


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${joseFin.className} antialiased`}
      >
      
      <Header1 />
      <Header2 />

        {children}
        <Footer />
      </body>
    </html>
  );
}
